package com.camel.redpenguin.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CAMEL_DEVICE_PUSH.
 */
public class CamelDevicePush {

    private Long id;
    private String devicePushWorkState;
    private String devicePushElectricMode;
    private String devicePushElectric;
    private String devicePushSignal;
    private String devicePushUrgency;
    private String devicePushStep;
    private String devicePushLocaMode;
    private String devicePushLatitude;
    private String devicePushLongtitude;
    private String devicePushIdentify;
    private String devicePushCreated;
    private String devicePushUpdated;

    public CamelDevicePush() {
    }

    public CamelDevicePush(Long id) {
        this.id = id;
    }

    public CamelDevicePush(Long id, String devicePushWorkState, String devicePushElectricMode, String devicePushElectric, String devicePushSignal, String devicePushUrgency, String devicePushStep, String devicePushLocaMode, String devicePushLatitude, String devicePushLongtitude, String devicePushIdentify, String devicePushCreated, String devicePushUpdated) {
        this.id = id;
        this.devicePushWorkState = devicePushWorkState;
        this.devicePushElectricMode = devicePushElectricMode;
        this.devicePushElectric = devicePushElectric;
        this.devicePushSignal = devicePushSignal;
        this.devicePushUrgency = devicePushUrgency;
        this.devicePushStep = devicePushStep;
        this.devicePushLocaMode = devicePushLocaMode;
        this.devicePushLatitude = devicePushLatitude;
        this.devicePushLongtitude = devicePushLongtitude;
        this.devicePushIdentify = devicePushIdentify;
        this.devicePushCreated = devicePushCreated;
        this.devicePushUpdated = devicePushUpdated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDevicePushWorkState() {
        return devicePushWorkState;
    }

    public void setDevicePushWorkState(String devicePushWorkState) {
        this.devicePushWorkState = devicePushWorkState;
    }

    public String getDevicePushElectricMode() {
        return devicePushElectricMode;
    }

    public void setDevicePushElectricMode(String devicePushElectricMode) {
        this.devicePushElectricMode = devicePushElectricMode;
    }

    public String getDevicePushElectric() {
        return devicePushElectric;
    }

    public void setDevicePushElectric(String devicePushElectric) {
        this.devicePushElectric = devicePushElectric;
    }

    public String getDevicePushSignal() {
        return devicePushSignal;
    }

    public void setDevicePushSignal(String devicePushSignal) {
        this.devicePushSignal = devicePushSignal;
    }

    public String getDevicePushUrgency() {
        return devicePushUrgency;
    }

    public void setDevicePushUrgency(String devicePushUrgency) {
        this.devicePushUrgency = devicePushUrgency;
    }

    public String getDevicePushStep() {
        return devicePushStep;
    }

    public void setDevicePushStep(String devicePushStep) {
        this.devicePushStep = devicePushStep;
    }

    public String getDevicePushLocaMode() {
        return devicePushLocaMode;
    }

    public void setDevicePushLocaMode(String devicePushLocaMode) {
        this.devicePushLocaMode = devicePushLocaMode;
    }

    public String getDevicePushLatitude() {
        return devicePushLatitude;
    }

    public void setDevicePushLatitude(String devicePushLatitude) {
        this.devicePushLatitude = devicePushLatitude;
    }

    public String getDevicePushLongtitude() {
        return devicePushLongtitude;
    }

    public void setDevicePushLongtitude(String devicePushLongtitude) {
        this.devicePushLongtitude = devicePushLongtitude;
    }

    public String getDevicePushIdentify() {
        return devicePushIdentify;
    }

    public void setDevicePushIdentify(String devicePushIdentify) {
        this.devicePushIdentify = devicePushIdentify;
    }

    public String getDevicePushCreated() {
        return devicePushCreated;
    }

    public void setDevicePushCreated(String devicePushCreated) {
        this.devicePushCreated = devicePushCreated;
    }

    public String getDevicePushUpdated() {
        return devicePushUpdated;
    }

    public void setDevicePushUpdated(String devicePushUpdated) {
        this.devicePushUpdated = devicePushUpdated;
    }

}
