package com.camel.redpenguin.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CAMEL_USER.
 */
public class CamelUser {

    private Long id;
    /** Not-null value. */
    private String userAccount;
    /** Not-null value. */
    private String userPassword;
    private String userPhonetype;
    private String userLatitude;
    private String userLongitude;
    private String userNike;
    private String userPhoneIdentify;
    private String userAdministrator;
    private String userUpdateDate;
    private String userCreateDate;

    public CamelUser() {
    }

    public CamelUser(Long id) {
        this.id = id;
    }

    public CamelUser(Long id, String userAccount, String userPassword, String userPhonetype, String userLatitude, String userLongitude, String userNike, String userPhoneIdentify, String userAdministrator, String userUpdateDate, String userCreateDate) {
        this.id = id;
        this.userAccount = userAccount;
        this.userPassword = userPassword;
        this.userPhonetype = userPhonetype;
        this.userLatitude = userLatitude;
        this.userLongitude = userLongitude;
        this.userNike = userNike;
        this.userPhoneIdentify = userPhoneIdentify;
        this.userAdministrator = userAdministrator;
        this.userUpdateDate = userUpdateDate;
        this.userCreateDate = userCreateDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserAccount() {
        return userAccount;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount;
    }

    /** Not-null value. */
    public String getUserPassword() {
        return userPassword;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public String getUserPhonetype() {
        return userPhonetype;
    }

    public void setUserPhonetype(String userPhonetype) {
        this.userPhonetype = userPhonetype;
    }

    public String getUserLatitude() {
        return userLatitude;
    }

    public void setUserLatitude(String userLatitude) {
        this.userLatitude = userLatitude;
    }

    public String getUserLongitude() {
        return userLongitude;
    }

    public void setUserLongitude(String userLongitude) {
        this.userLongitude = userLongitude;
    }

    public String getUserNike() {
        return userNike;
    }

    public void setUserNike(String userNike) {
        this.userNike = userNike;
    }

    public String getUserPhoneIdentify() {
        return userPhoneIdentify;
    }

    public void setUserPhoneIdentify(String userPhoneIdentify) {
        this.userPhoneIdentify = userPhoneIdentify;
    }

    public String getUserAdministrator() {
        return userAdministrator;
    }

    public void setUserAdministrator(String userAdministrator) {
        this.userAdministrator = userAdministrator;
    }

    public String getUserUpdateDate() {
        return userUpdateDate;
    }

    public void setUserUpdateDate(String userUpdateDate) {
        this.userUpdateDate = userUpdateDate;
    }

    public String getUserCreateDate() {
        return userCreateDate;
    }

    public void setUserCreateDate(String userCreateDate) {
        this.userCreateDate = userCreateDate;
    }

}
