package com.camel.redpenguin.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CAMEL_DEVICE_HISTORY.
 */
public class CamelDeviceHistory {

    private Long id;
    private String deviceHistoryType;
    private String deviceHistoryLatitude;
    private String deviceHistoryLongtitude;
    private String deviceHistoryIdentify;
    private String deviceHistoryPage;
    private String deviceHistoryStep;
    private String deviceHistoryCreated;
    private String deviceHistoryTermination;
    private String deviceHistoryAllTime;

    public CamelDeviceHistory() {
    }

    public CamelDeviceHistory(Long id) {
        this.id = id;
    }

    public CamelDeviceHistory(Long id, String deviceHistoryType, String deviceHistoryLatitude, String deviceHistoryLongtitude, String deviceHistoryIdentify, String deviceHistoryPage, String deviceHistoryStep, String deviceHistoryCreated, String deviceHistoryTermination, String deviceHistoryAllTime) {
        this.id = id;
        this.deviceHistoryType = deviceHistoryType;
        this.deviceHistoryLatitude = deviceHistoryLatitude;
        this.deviceHistoryLongtitude = deviceHistoryLongtitude;
        this.deviceHistoryIdentify = deviceHistoryIdentify;
        this.deviceHistoryPage = deviceHistoryPage;
        this.deviceHistoryStep = deviceHistoryStep;
        this.deviceHistoryCreated = deviceHistoryCreated;
        this.deviceHistoryTermination = deviceHistoryTermination;
        this.deviceHistoryAllTime = deviceHistoryAllTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceHistoryType() {
        return deviceHistoryType;
    }

    public void setDeviceHistoryType(String deviceHistoryType) {
        this.deviceHistoryType = deviceHistoryType;
    }

    public String getDeviceHistoryLatitude() {
        return deviceHistoryLatitude;
    }

    public void setDeviceHistoryLatitude(String deviceHistoryLatitude) {
        this.deviceHistoryLatitude = deviceHistoryLatitude;
    }

    public String getDeviceHistoryLongtitude() {
        return deviceHistoryLongtitude;
    }

    public void setDeviceHistoryLongtitude(String deviceHistoryLongtitude) {
        this.deviceHistoryLongtitude = deviceHistoryLongtitude;
    }

    public String getDeviceHistoryIdentify() {
        return deviceHistoryIdentify;
    }

    public void setDeviceHistoryIdentify(String deviceHistoryIdentify) {
        this.deviceHistoryIdentify = deviceHistoryIdentify;
    }

    public String getDeviceHistoryPage() {
        return deviceHistoryPage;
    }

    public void setDeviceHistoryPage(String deviceHistoryPage) {
        this.deviceHistoryPage = deviceHistoryPage;
    }

    public String getDeviceHistoryStep() {
        return deviceHistoryStep;
    }

    public void setDeviceHistoryStep(String deviceHistoryStep) {
        this.deviceHistoryStep = deviceHistoryStep;
    }

    public String getDeviceHistoryCreated() {
        return deviceHistoryCreated;
    }

    public void setDeviceHistoryCreated(String deviceHistoryCreated) {
        this.deviceHistoryCreated = deviceHistoryCreated;
    }

    public String getDeviceHistoryTermination() {
        return deviceHistoryTermination;
    }

    public void setDeviceHistoryTermination(String deviceHistoryTermination) {
        this.deviceHistoryTermination = deviceHistoryTermination;
    }

    public String getDeviceHistoryAllTime() {
        return deviceHistoryAllTime;
    }

    public void setDeviceHistoryAllTime(String deviceHistoryAllTime) {
        this.deviceHistoryAllTime = deviceHistoryAllTime;
    }

}
