package com.camel.redpenguin.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CAMEL_DEVICE.
 */
public class CamelDevice {

    private Long id;
    private String deviceNike;
    private String deviceAvatar;
    private String deviceLatitude;
    private String deviceLongitude;
    private String deviceFrequency;
    private String deviceLocationMode;
    private String deviceIdentify;
    private String deviceSelect;
    private String deviceLigature;
    private String deviceUpdateDate;
    private String deviceCreateDate;

    public CamelDevice() {
    }

    public CamelDevice(Long id) {
        this.id = id;
    }

    public CamelDevice(Long id, String deviceNike, String deviceAvatar, String deviceLatitude, String deviceLongitude, String deviceFrequency, String deviceLocationMode, String deviceIdentify, String deviceSelect, String deviceLigature, String deviceUpdateDate, String deviceCreateDate) {
        this.id = id;
        this.deviceNike = deviceNike;
        this.deviceAvatar = deviceAvatar;
        this.deviceLatitude = deviceLatitude;
        this.deviceLongitude = deviceLongitude;
        this.deviceFrequency = deviceFrequency;
        this.deviceLocationMode = deviceLocationMode;
        this.deviceIdentify = deviceIdentify;
        this.deviceSelect = deviceSelect;
        this.deviceLigature = deviceLigature;
        this.deviceUpdateDate = deviceUpdateDate;
        this.deviceCreateDate = deviceCreateDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceNike() {
        return deviceNike;
    }

    public void setDeviceNike(String deviceNike) {
        this.deviceNike = deviceNike;
    }

    public String getDeviceAvatar() {
        return deviceAvatar;
    }

    public void setDeviceAvatar(String deviceAvatar) {
        this.deviceAvatar = deviceAvatar;
    }

    public String getDeviceLatitude() {
        return deviceLatitude;
    }

    public void setDeviceLatitude(String deviceLatitude) {
        this.deviceLatitude = deviceLatitude;
    }

    public String getDeviceLongitude() {
        return deviceLongitude;
    }

    public void setDeviceLongitude(String deviceLongitude) {
        this.deviceLongitude = deviceLongitude;
    }

    public String getDeviceFrequency() {
        return deviceFrequency;
    }

    public void setDeviceFrequency(String deviceFrequency) {
        this.deviceFrequency = deviceFrequency;
    }

    public String getDeviceLocationMode() {
        return deviceLocationMode;
    }

    public void setDeviceLocationMode(String deviceLocationMode) {
        this.deviceLocationMode = deviceLocationMode;
    }

    public String getDeviceIdentify() {
        return deviceIdentify;
    }

    public void setDeviceIdentify(String deviceIdentify) {
        this.deviceIdentify = deviceIdentify;
    }

    public String getDeviceSelect() {
        return deviceSelect;
    }

    public void setDeviceSelect(String deviceSelect) {
        this.deviceSelect = deviceSelect;
    }

    public String getDeviceLigature() {
        return deviceLigature;
    }

    public void setDeviceLigature(String deviceLigature) {
        this.deviceLigature = deviceLigature;
    }

    public String getDeviceUpdateDate() {
        return deviceUpdateDate;
    }

    public void setDeviceUpdateDate(String deviceUpdateDate) {
        this.deviceUpdateDate = deviceUpdateDate;
    }

    public String getDeviceCreateDate() {
        return deviceCreateDate;
    }

    public void setDeviceCreateDate(String deviceCreateDate) {
        this.deviceCreateDate = deviceCreateDate;
    }

}
