package com.camel.redpenguin.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.camel.redpenguin.greendao.CamelUser;
import com.camel.redpenguin.greendao.CamelDevice;
import com.camel.redpenguin.greendao.CamelDevicePush;
import com.camel.redpenguin.greendao.DataRelFamily;
import com.camel.redpenguin.greendao.RelSafetyZone;
import com.camel.redpenguin.greendao.CamelDeviceHistory;

import com.camel.redpenguin.greendao.CamelUserDao;
import com.camel.redpenguin.greendao.CamelDeviceDao;
import com.camel.redpenguin.greendao.CamelDevicePushDao;
import com.camel.redpenguin.greendao.DataRelFamilyDao;
import com.camel.redpenguin.greendao.RelSafetyZoneDao;
import com.camel.redpenguin.greendao.CamelDeviceHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig camelUserDaoConfig;
    private final DaoConfig camelDeviceDaoConfig;
    private final DaoConfig camelDevicePushDaoConfig;
    private final DaoConfig dataRelFamilyDaoConfig;
    private final DaoConfig relSafetyZoneDaoConfig;
    private final DaoConfig camelDeviceHistoryDaoConfig;

    private final CamelUserDao camelUserDao;
    private final CamelDeviceDao camelDeviceDao;
    private final CamelDevicePushDao camelDevicePushDao;
    private final DataRelFamilyDao dataRelFamilyDao;
    private final RelSafetyZoneDao relSafetyZoneDao;
    private final CamelDeviceHistoryDao camelDeviceHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        camelUserDaoConfig = daoConfigMap.get(CamelUserDao.class).clone();
        camelUserDaoConfig.initIdentityScope(type);

        camelDeviceDaoConfig = daoConfigMap.get(CamelDeviceDao.class).clone();
        camelDeviceDaoConfig.initIdentityScope(type);

        camelDevicePushDaoConfig = daoConfigMap.get(CamelDevicePushDao.class).clone();
        camelDevicePushDaoConfig.initIdentityScope(type);

        dataRelFamilyDaoConfig = daoConfigMap.get(DataRelFamilyDao.class).clone();
        dataRelFamilyDaoConfig.initIdentityScope(type);

        relSafetyZoneDaoConfig = daoConfigMap.get(RelSafetyZoneDao.class).clone();
        relSafetyZoneDaoConfig.initIdentityScope(type);

        camelDeviceHistoryDaoConfig = daoConfigMap.get(CamelDeviceHistoryDao.class).clone();
        camelDeviceHistoryDaoConfig.initIdentityScope(type);

        camelUserDao = new CamelUserDao(camelUserDaoConfig, this);
        camelDeviceDao = new CamelDeviceDao(camelDeviceDaoConfig, this);
        camelDevicePushDao = new CamelDevicePushDao(camelDevicePushDaoConfig, this);
        dataRelFamilyDao = new DataRelFamilyDao(dataRelFamilyDaoConfig, this);
        relSafetyZoneDao = new RelSafetyZoneDao(relSafetyZoneDaoConfig, this);
        camelDeviceHistoryDao = new CamelDeviceHistoryDao(camelDeviceHistoryDaoConfig, this);

        registerDao(CamelUser.class, camelUserDao);
        registerDao(CamelDevice.class, camelDeviceDao);
        registerDao(CamelDevicePush.class, camelDevicePushDao);
        registerDao(DataRelFamily.class, dataRelFamilyDao);
        registerDao(RelSafetyZone.class, relSafetyZoneDao);
        registerDao(CamelDeviceHistory.class, camelDeviceHistoryDao);
    }
    
    public void clear() {
        camelUserDaoConfig.getIdentityScope().clear();
        camelDeviceDaoConfig.getIdentityScope().clear();
        camelDevicePushDaoConfig.getIdentityScope().clear();
        dataRelFamilyDaoConfig.getIdentityScope().clear();
        relSafetyZoneDaoConfig.getIdentityScope().clear();
        camelDeviceHistoryDaoConfig.getIdentityScope().clear();
    }

    public CamelUserDao getCamelUserDao() {
        return camelUserDao;
    }

    public CamelDeviceDao getCamelDeviceDao() {
        return camelDeviceDao;
    }

    public CamelDevicePushDao getCamelDevicePushDao() {
        return camelDevicePushDao;
    }

    public DataRelFamilyDao getDataRelFamilyDao() {
        return dataRelFamilyDao;
    }

    public RelSafetyZoneDao getRelSafetyZoneDao() {
        return relSafetyZoneDao;
    }

    public CamelDeviceHistoryDao getCamelDeviceHistoryDao() {
        return camelDeviceHistoryDao;
    }

}
